import './globals.css';
import DarkModeToggle from '../components/DarkModeToggle';
import NavWrapper       from '../components/NavWrapper';
import {
  HomeIcon, TrophyIcon, PlusIcon,
  CalendarIcon, UserIcon
} from 'lucide-react';

import { Inter } from 'next/font/google';


// recuperás la Inter por defecto
const inter = Inter({ subsets: ['latin'] });

export const metadata = {
  title: 'Mi App Loca',
  description: 'Generated by create-next-app',
};

export default function RootLayout({ children }) {
  const navItems = [
    /* tus items aquí, o los podés extraer a un JSON */
    { icon: <HomeIcon />,      label: 'Inicio',   active: true,  onClick: ()=>{} },
    { icon: <TrophyIcon/>,     label: 'Torneos',  active: false, onClick: ()=>{} },
    { icon: <PlusIcon/>,       label: 'Crear',    active: false, onClick: ()=>{} },
    { icon: <CalendarIcon/>,   label: 'Calendario',active: false, onClick: ()=>{} },
    { icon: <UserIcon/>,       label: 'Perfil',   active: false, onClick: ()=>{} },
  ];

  return (
    <html lang="es" className={inter.className}>
      <body className="min-h-screen flex flex-col">
        <header className="p-4 flex justify-end">
          <DarkModeToggle />
        </header>
        <main className="flex-grow p-6">
          {children}
        </main>
        <NavWrapper />
      </body>
    </html>
  );
}
